# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_designation_and_employee_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='source',
            field=models.CharField(db_index=True, default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['employee', '-timestamp'], name='audit_ulog_emp_ts'),
        ),
    ]
