# Generated by Django 4.2 on 2026-02-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_userloginlog_employee_source_alter_userloginlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='source',
            field=models.CharField(choices=[('web', 'Web (Admin/Dashboard)'), ('app', 'App')], db_index=True, default='web', max_length=10),
        ),
    ]
