# Generated by Django 4.2 on 2026-01-23 17:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic location (longitude, latitude)', srid=4326)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('accuracy', models.FloatField(help_text='Location accuracy in meters')),
                ('battery_level', models.IntegerField(help_text='Battery percentage (0-100)')),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('address', models.TextField(blank=True, help_text='Reverse geocoded address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Location Log',
                'verbose_name_plural': 'Location Logs',
                'db_table': 'location_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['employee', '-timestamp'], name='idx_employee_timestamp'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['-timestamp'], name='idx_timestamp'),
        ),
        migrations.AddIndex(
            model_name='locationlog',
            index=models.Index(fields=['employee'], name='idx_employee'),
        ),
    ]
