# Generated by Django 4.2 on 2026-02-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_add_last_seen_heartbeat_fields'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAnomaly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('high_speed', 'High speed'), ('long_jump', 'Long jump'), ('night_activity', 'Night activity')], db_index=True, max_length=50)),
                ('score', models.FloatField(default=1.0, help_text='Relative severity score')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra context (times, distances, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_anomalies', to='employees.employee')),
            ],
            options={
                'db_table': 'location_anomalies',
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='locationanomaly',
            index=models.Index(fields=['employee', '-date'], name='idx_anom_employee_date'),
        ),
        migrations.AddIndex(
            model_name='locationanomaly',
            index=models.Index(fields=['reason', '-date'], name='idx_anom_reason_date'),
        ),
        migrations.AlterUniqueTogether(
            name='locationanomaly',
            unique_together={('employee', 'date', 'reason')},
        ),
    ]
