# Generated by Django 4.2 on 2026-01-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('first_location_time', models.TimeField(blank=True, help_text='Time of first location log', null=True)),
                ('last_location_time', models.TimeField(blank=True, help_text='Time of last location log', null=True)),
                ('check_in_time', models.TimeField(blank=True, help_text='Official check-in time', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Official check-out time', null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours worked', max_digits=5)),
                ('total_locations_logged', models.IntegerField(default=0, help_text='Number of location logs for the day')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half-Day'), ('ABSENT', 'Absent')], db_index=True, default='PRESENT', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', '-date'], name='idx_emp_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['-date'], name='idx_date'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'status'], name='idx_emp_status'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
