# Generated by Django 4.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_duty_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutysession',
            name='remarks',
            field=models.TextField(blank=True, help_text='Auto-end reason or manual note', null=True),
        ),
    ]
