# Generated by Django 4.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_dutysession_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutysession',
            name='total_hours',
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text='Hours for this session (set when end_time is set)',
                max_digits=7,
            ),
        ),
    ]
