# Generated by Django 4.2 on 2026-02-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_device_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='employee_de_employe_ef1407_idx',
            old_name='emp_devicetok_emp_plat_idx',
        ),
    ]
