# Generated by Django 4.2 on 2026-07-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todotask',
            new_name='todo_tasks_employe_1f7ae3_idx',
            old_name='todo_tasks_employe_0f0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='todotask',
            new_name='todo_tasks_employe_1bfaff_idx',
            old_name='todo_tasks_employe_7a8b2a_idx',
        ),
    ]
